
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CLASS COLON COMMA DEDENT DEF IDENTIFIER INDENT LPAREN NEWLINE RPARENprogram : declarationsdeclarations : declarations class_declaration\n                    | declarations function_declaration\n                    | emptyclass_declaration : CLASS IDENTIFIER COLON NEWLINE INDENT declarations DEDENTfunction_declaration : DEF IDENTIFIER LPAREN parameters RPAREN COLON NEWLINE INDENT declarations DEDENTparameters : parameters COMMA IDENTIFIER\n                  | IDENTIFIER\n                  | emptyempty :'
    
_lr_action_items = {'CLASS':([0,2,3,4,5,16,19,22,24,25,26,],[-10,6,-4,-2,-3,-10,6,-5,-10,6,-6,]),'DEF':([0,2,3,4,5,16,19,22,24,25,26,],[-10,7,-4,-2,-3,-10,7,-5,-10,7,-6,]),'$end':([0,1,2,3,4,5,22,26,],[-10,0,-1,-4,-2,-3,-5,-6,]),'DEDENT':([3,4,5,16,19,22,24,25,26,],[-4,-2,-3,-10,22,-5,-10,26,-6,]),'IDENTIFIER':([6,7,11,18,],[8,9,13,21,]),'COLON':([8,17,],[10,20,]),'LPAREN':([9,],[11,]),'NEWLINE':([10,20,],[12,23,]),'RPAREN':([11,13,14,15,21,],[-10,-8,17,-9,-7,]),'COMMA':([11,13,14,15,21,],[-10,-8,18,-9,-7,]),'INDENT':([12,23,],[16,24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'declarations':([0,16,24,],[2,19,25,]),'empty':([0,11,16,24,],[3,15,3,3,]),'class_declaration':([2,19,25,],[4,4,4,]),'function_declaration':([2,19,25,],[5,5,5,]),'parameters':([11,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> declarations','program',1,'p_program','newParse.py',43),
  ('declarations -> declarations class_declaration','declarations',2,'p_declarations','newParse.py',47),
  ('declarations -> declarations function_declaration','declarations',2,'p_declarations','newParse.py',48),
  ('declarations -> empty','declarations',1,'p_declarations','newParse.py',49),
  ('class_declaration -> CLASS IDENTIFIER COLON NEWLINE INDENT declarations DEDENT','class_declaration',7,'p_class_declaration','newParse.py',53),
  ('function_declaration -> DEF IDENTIFIER LPAREN parameters RPAREN COLON NEWLINE INDENT declarations DEDENT','function_declaration',10,'p_function_declaration','newParse.py',57),
  ('parameters -> parameters COMMA IDENTIFIER','parameters',3,'p_parameters','newParse.py',61),
  ('parameters -> IDENTIFIER','parameters',1,'p_parameters','newParse.py',62),
  ('parameters -> empty','parameters',1,'p_parameters','newParse.py',63),
  ('empty -> <empty>','empty',0,'p_empty','newParse.py',70),
]
